config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'
  resources :notes

  authenticated :user do
    root 'notes#index' , as:"authenticated_root"
  end

  root 'welcome#index'


end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :find_note , only: [:show , :edit , :destroy , :update]
  def index
    @notes = current_user.notes.order("created_at DESC")
  end


  def show

  end

  def new
    @note = current_user.notes.build()

  end

  def edit

  end

  def create
    @note = current_user.notes.build(note_params)

    if @note.save
      redirect_to @note

    else
      render :new
    end


  end

  def update
    if @note.update(note_params)
      redirect_to :note
    else
      render :edit
    end

  end

  def destroy
    @note.destroy
    redirect_to notes_path


  end

  private
  def find_note

    @note = Note.find(params[:id])

  end

  def note_params
    params.require(:note).permit(:title,:content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteBook | Your online Notebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="header_inner">
    <%= link_to image_tag('logo.svg') , root_path , id: "logo" %>
    <nav>
      <% if user_signed_in? %>

      <%= link_to "New Note", new_note_path %>
          <%= link_to "Sign Out" , destroy_user_session_path , method: :delete%>

        <% else %>
      <%= link_to "Log in" , new_user_session_path %>

      <%end  %>
    </nav>
  </div>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



<%= yield %>

</body>
</html>

app/views/notes/_form.erb
<%= simple_form_for @note do  |f| %>

    <%= f.input :title  %>
    <%= f.input :content %>
    <%= f.button :submit , class:"button" %>


<% end %>

app/views/notes/edit.html.erb
<div class="wrapper_with_padding">
  <%= render 'notes/form' %>

  <%= link_to "Cancel" , note_path(@note) %>

</div>

app/views/notes/index.html.erb
<h1>Index Path</h1>


<div class="wrapper_with_padding">
  <div id="notes" class="clearfix">

    <% unless @notes.blank?  %>

        <% @notes.each do |note|%>
            <a href= <%= note_path(note) %> >
              <div class="note">
                <h2 class="title"><%= note.title %></h2>
                <p class="date"><%= time_ago_in_words(note.created_at) %></p>
              </div>
            </a>



  <%end %>


    <% else  %>
        <h2>Add a Note</h2>
        <p>It appears yuo havent created any notes yet , lets fix that</p>
        <button><%= link_to "New Note" , new_note_path %></button>

    <% end  %>





  </div>



  <%= link_to "New Note" , new_note_path %>

</div>

app/views/notes/new.html.erb
<div class="wrapper_with_padding">
  <h1>Add a new note</h1>
  <%= render 'notes/form' %>
</div>

app/views/notes/show.html.erb
<div class="wrapper_with_padding">
  <div id="note_show">
    <h1 class="title">
      <%= @note.title %>
    </h1>
    <p>
      <%= simple_format(@note.content) %>
    </p>
    <div class="buttons">
      <%= link_to "Edit", edit_note_path(@note), class: "button" %>
      <%= link_to "Delete", note_path(@note), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>NoteNote</h1>

    <p>Your online Notebook never forget an idea again</p>

    <button><%= link_to "Sign Up" , new_user_registration_path %></button>
  </div>
</div>


<div id="testimonial">
  <div class="wrapper">
    <p class="quote">"The greatest notebook application. Period"</p>
    <p class="name">-Ismail El-Habbash</p>
  </div>
</div>

<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">

      <div class="callout">
        <i class="fa fa-pencil"></i>
        <h2>Notes</h2>
        <p>Lstandard dummy text centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus Page</p>
      </div>

      <div class="callout">
        <i class="fa fa-rocket"></i>

        <h2>Rocket</h2>
        <p>t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look </p>
      </div>

      <div class="callout">
        <i class="fa fa-bolt"></i>

        <h2>Lightning</h2>
        <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydne</p>
      </div>
    </div>
  </div>
</div>


<div id="bottom_cta">
  <div class="wrapper">
    <h2>For Realz</h2>
    <p>I want you to sign up... If you don't , I will find you!</p>
    <button><%= link_to "click me" , new_user_registration_path %></button>
  </div>
</div>

<footer>
  <p>&copy Ismail EL Habbash</p>
</footer>